name: Checks

on: [push]

jobs:
  test-lints:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t myapp .

      - name: List Files in Container
        run: docker run --rm myapp sh -c "ls -al /app"

      - name: Verify Python Installation
        run: docker run --rm myapp sh -c "/py/bin/python --version"

      - name: Verify `manage.py` Existence
        run: docker run --rm myapp sh -c "test -f /app/manage.py && echo 'manage.py found' || echo 'manage.py missing'"

      - name: Verify flake8 Installation
        run: docker run --rm myapp sh -c "/py/bin/flake8 --version || echo 'flake8 not found'"

      - name: Run Tests
        run: docker run --rm myapp sh -c "/py/bin/python /app/manage.py test"

      - name: Lint
        run: docker run --rm myapp sh -c "/py/bin/flake8"
