---
name: Checks

on: [push]

jobs:
  test-lints:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker Image
        run: docker-compose build

      - name: List Files in Container
        run: docker-compose run --rm app sh -c "ls -al /app"

      - name: Verify Python Installation
        run: docker-compose run --rm app sh -c "/py/bin/python --version"

      - name: Verify `manage.py` Existence
        run: docker-compose run --rm app sh -c "test -f /app/manage.py && echo 'manage.py found' || echo 'manage.py missing'"

      - name: Verify flake8 Installation
        run: docker-compose run --rm app sh -c "/py/bin/flake8 --version || echo 'flake8 not found'"

      - name: Run Tests
        run: docker-compose run --rm app sh -c "/py/bin/python /app/manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "/py/bin/flake8"
